# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  vmImage: 'ubantu-latest'

steps:
  - checkout: self

  - task: Docker@2
    inputs:
      containerRegistry: 'DockerRegistry'
      repository: 'ckAKSRG'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'